spring:
  application:
    name: share-books
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger

server:
  port: 8080
  servlet:
    context-path: /api/v1/

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 8640000
    mail:
      frontend:
        activation-url: http://localhost:4200/activate-account
